apiVersion: apps/v1
kind: Deployment
metadata:
  name: wedding-deployment
  labels:
    app: wedding
spec:
  replicas: 6
  selector:
    matchLabels:
      app: wedding
  template:
    metadata:
      labels:
        app: wedding
    spec:
      containers:
        - name: wedding
          image: iaktech/wedding:latest
          ports:
            - containerPort: 8080
          
